In [8]:
import pandas as pd
import statistics as stats

In [20]:
# Mapped read counts for each BAM file with corrected keys if necessary
mapped_reads = {
    'merged_CV-H3K9ac_1.sort.bam': 31868965,
    'merged_CV-H3K9ac_2.sort.bam': 27094693,
    'merged_CV-H3K9ac_3.sort.bam': 43558764,
    'merged_CV-H3K9ac_4.sort.bam': 17689102,
    'merged_CV-H3K9ac_5.sort.bam': 12941845,
    'merged_CV-H3K9ac_6.sort.bam': 11526573,
    'GF-H3K9ac_1.sort.bam': 23181470,
    'GF-H3K9ac_2.sort.bam': 32969015,
    'GF-H3K9ac_3.sort.bam': 26425333,
    'GF-H3K9ac_4.sort.bam': 25698509,
}

for val in mapped_reads.values():
    print(val)

31868965
27094693
43558764
17689102
12941845
11526573
23181470
32969015
26425333
25698509

In [23]:
df = pd.read_csv('total_count_table_intersect.txt', sep='\t', index_col=0)
for i in range(10):
    col = df.iloc[:,i]
    print(sum(col))

df

746870
808636
1672671
650925
610352
298326
1800281
2048885
1817454
2445793

,read_counts_per_gene_CV-H3K9ac_1.txt,read_counts_per_gene_CV-H3K9ac_2.txt,read_counts_per_gene_CV-H3K9ac_3.txt,read_counts_per_gene_CV-H3K9ac_4.txt,read_counts_per_gene_CV-H3K9ac_5.txt,read_counts_per_gene_CV-H3K9ac_6.txt,read_counts_per_gene_GF-H3K9ac_1.txt,read_counts_per_gene_GF-H3K9ac_2.txt,read_counts_per_gene_GF-H3K9ac_3.txt,read_counts_per_gene_GF-H3K9ac_4.txt
gene,,,,,,,,,,
0610005C13Rik,25,40,50,34,22,17,89,71,66,110
0610007C21Rik,69,78,177,75,67,21,245,327,224,304
0610007L01Rik,25,25,38,18,15,13,45,16,31,21
0610007N19Rik,48,74,197,86,88,25,248,302,256,360
0610007P08Rik,59,74,224,78,66,31,266,373,277,382
...,...,...,...,...,...,...,...,...,...,...
Zyx,44,59,142,61,70,25,168,229,177,269
Zzef1,59,77,217,94,75,33,299,366,326,451
Zzz3,56,75,166,73,84,27,265,293,245,405
a,36,22,26,11,13,5,23,25,22,14
l7Rn6,36,33,57,11,16,7,61,52,63,97

In [25]:
df = pd.read_csv('final_counts_matrix.csv', sep=',', index_col=0)

for i in range(10):
    col = df.iloc[:,i]
    print(sum(col))

# #20,412,845 < 31,868,965
df

20412845
24906190
21094428
23387708
5682594
8518177
10256547
23982514
14181194
14297788

,GF-H3K9ac_1,GF-H3K9ac_4,GF-H3K9ac_3,GF-H3K9ac_2,merged_CV-H3K9ac_6,merged_CV-H3K9ac_5,merged_CV-H3K9ac_4,merged_CV-H3K9ac_3,merged_CV-H3K9ac_2,merged_CV-H3K9ac_1
GeneName,,,,,,,,,,
0610005C13Rik,0,0,0,0,0,0,0,0,0,0
0610007C21Rik,1360,1850,1410,1905,204,497,411,1256,560,472
0610007L01Rik,1158,1401,1206,1249,322,556,595,1279,827,810
0610007N19Rik,0,0,0,0,0,0,0,0,0,0
0610007P08Rik,2129,2616,2273,2872,514,811,975,2619,1352,1566
...,...,...,...,...,...,...,...,...,...,...
Zyx,4021,5081,4033,4993,506,1388,1563,3906,1589,1193
Zzef1,3417,4283,3812,3860,1223,1454,1725,4163,2549,2941
Zzz3,2707,3356,2651,3231,625,1000,1134,2753,1515,1569
a,331,430,355,346,56,122,135,328,210,209
l7Rn6,374,466,392,399,83,161,181,433,253,271

In [28]:
df = pd.read_csv('final_counts_matrix_2000.csv', sep=',', index_col=0)

for i in range(10):
    col = df.iloc[:,i]
    print(df.columns[i])
    print(sum(col))

# #20,412,845 < 31,868,965
df

GF-H3K9ac_1
11918283
GF-H3K9ac_4
14682096
GF-H3K9ac_3
12208581
GF-H3K9ac_2
13688984
merged_CV-H3K9ac_6
2991311
merged_CV-H3K9ac_5
4853793
merged_CV-H3K9ac_4
5704475
merged_CV-H3K9ac_3
13373836
merged_CV-H3K9ac_2
7650832
merged_CV-H3K9ac_1
7472546

,GF-H3K9ac_1,GF-H3K9ac_4,GF-H3K9ac_3,GF-H3K9ac_2,merged_CV-H3K9ac_6,merged_CV-H3K9ac_5,merged_CV-H3K9ac_4,merged_CV-H3K9ac_3,merged_CV-H3K9ac_2,merged_CV-H3K9ac_1
GeneName,,,,,,,,,,
0610005C13Rik,0,0,0,0,0,0,0,0,0,0
0610007C21Rik,939,1314,966,1370,134,341,274,864,354,271
0610007L01Rik,746,952,790,856,176,372,366,798,452,415
0610007N19Rik,0,0,0,0,0,0,0,0,0,0
0610007P08Rik,1483,1982,1564,2050,259,566,620,1677,804,864
...,...,...,...,...,...,...,...,...,...,...
Zyx,2670,3215,2639,3319,298,890,1021,2568,996,726
Zzef1,1923,2424,2115,2244,615,798,938,2245,1331,1509
Zzz3,1826,2264,1701,2249,373,731,743,1816,870,913
a,211,283,225,210,28,78,73,214,118,117
l7Rn6,283,364,300,283,47,108,122,266,154,174

In [10]:
df = pd.read_csv('count_table_merged.txt', sep='\t', index_col=0)

# for i in range(0, len(df.columns)):
#     df.iloc[:, i] = df.iloc[:, i] / df.iloc[:, i].sum()

col1 = df.iloc[:,0]
sum(col1)
# mappe reads from samtools view -c -F 4 merged_CV-H3K9ac_1.sort.bam -> 31,868,965

84651833

In [11]:
df = pd.read_csv('countCV1.txt', sep='\t', index_col=0)

col1 = df.iloc[:,0]
sum(col1)

847788

In [12]:
df = pd.read_csv('countCV1_2.txt', sep='\t', index_col=0)

col1 = df.iloc[:,0]
sum(col1)

8424

In [9]:
col1 = df.iloc[:,0]
stats.median(col1)
# total read count to tss -> 84,651,833
#84,651,833 > 31,868,965 ???

2892